const REQUEST_DATA = 0;
const UPDATE_INFO = 3;

const DRY_CLOTHES = 1;
const COLLECT_CLOTHES = 2;
const PAUSE_MOTOR = 3;
const RESUME_MOTOR = 4;
const START_DRYER_MOBILE = 7;
const STOP_DRYER = 9;

export {
  REQUEST_DATA,
  DRY_CLOTHES,
  COLLECT_CLOTHES,
  PAUSE_MOTOR,
  RESUME_MOTOR,
  START_DRYER_MOBILE,
  STOP_DRYER,
  UPDATE_INFO,
};